### ISSUE TITLE
Specification Extensions are not supported - x- is prohibited

### ISSUE THREAD

**Issue by commonism** [python-lapidary/lapidary#40]
Hi,

using f57d401

```
~/venv/lapidary/bin/lapidary init openapi/openapi.yaml lib dsp8010
…
pydantic.error_wrappers.ValidationError: 194 validation errors for OpenApiModel
info -> x-copyright
  extra fields not permitted (type=value_error.extra)
paths -> __root__ -> /redfish/v1/Chassis/{ChassisId}/MediaControllers -> get -> x-deprecatedReason
  extra fields not permitted (type=value_error.extra)
paths -> __root__ -> /redfish/v1/Chassis/{ChassisId}/MediaControllers -> get -> x-versionDeprecated
  extra fields not permitted (type=value_error.extra)
paths -> __root__ -> /redfish/v1/Chassis/{ChassisId}/MediaControllers -> $ref
  field required (type=value_error.missing)
paths -> __root__ -> /redfish/v1/Chassis/{ChassisId}/MediaControllers -> get
  extra fields not permitted (type=value_error.extra)
```

This is unfortunate as I consider (this part of the) input data valid OpenAPI.
It's the DSP8010 OpenAPI description document of the Redfish protocol by the DMTF. [archive](https://www.dmtf.org/sites/default/files/standards/documents/DSP8010_2022.2.zip) [live](https://redfish.dmtf.org/schemas/v1/openapi.yaml)
The x- is questions in the (Specification Extensions)[https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#specification-extensions].

**Comment by rafalkrupinski** [comment]
The naive approach would be to change the OpenAPI model classes to read `Config.extra=Ignore` or `Allow` instead of `Forbid`. You can try it to see if you get any other errors.

Unfortunately it would allow all keys, not just those matching `^x-`. I'm pretty sure Pydantic validators have a solution to this. I'll take a look, unless you'd like to.

**Comment by rafalkrupinski** [comment]
I found a few other things that Lapidary doesn't currently support to run this schema:
- multi-file schemas (external $refs)
- operations without operationId

Also a single stub file with nearly 2000 methods would be very slow for tools to read. [GSMTasks](https://github.com/lapidary-library/gsmtasks/) has 150 and it's sluggish.

I think all those issues should be handled at some point.

**Comment by commonism** [comment]
> I'm pretty sure Pydantic validators have a solution to this. I'll take a look, unless you'd like to.

I use a pre validator to remove x-* from the data.

https://github.com/commonism/aiopenapi3/blob/c619ee9fcfc3780b64bc6c53eee61158123a44d8/aiopenapi3/base.py#L30-L52
