### ISSUE TITLE
Support python 3.13

### ISSUE THREAD

**Issue by rafalkrupinski** [python-lapidary/lapidary#71]
Blockers:
- falconry/python-mimeparse#48

**Comment by vytas7** [comment]
Hi! :wave:
I have now released [`python-mimeparse==2.0.0rc1`](https://pypi.org/project/python-mimeparse/2.0.0rc1/), please take it for a spin (`pip install python-mimeparse==2.0.0rc1`), and let me know if you run into any issues!

**Comment by rafalkrupinski** [comment]
thank you @vytas7 , I'm monitoring the issue :)
I'll try it in the coming days.

**Comment by rafalkrupinski** [comment]
Resolved in c987f820b6eb45bcb9bdd6178021b41dbeea450a
